### ISSUE TITLE
Bump to 1.2

### ISSUE THREAD

**Issue by jallits** [rweas/my-installer#1]

**Comment by rweas** [comment]
Sorry what does that mean?

**Comment by jallits** [comment]
Crap I thought I edited this issue immediately after publishing it. In the laravel file in the project root, I was suggesting bumping the version up to 1.2. Since this does not introduce breaking changes and it adds new functionality, this would be next version semantically.

**Comment by jallits** [comment]
Probably should squash the commits for the PR.

**Comment by rweas** [comment]
Yeah. And you didn't edit this one you just created a new issue. Thanks @jallits  for all the help this is my first major PR!
And I'm going to squash just as soon as I'm sure everything is good.

**Comment by rweas** [comment]
I did it a few hours ago.
